<?php

class User {
    public $id;
    public $name;
    public $ic;

    public function save() {
        // save the user to the db and update $this->id with autogenerated id
    }

    public function addChild(User $child) {
        // add to `Relations`: [$this->id, $child->id, 'father']
        // then add to `Relations`: [$child->id, $this->id, 'child']
    }

    public function addWife(User $wife) {
        // check if  this user already has a wife and throw an Exception "Wife already exists"
        // 
        // add to `Relations`: [$this->id, $wife->id, 'husband']
        // then add to `Relations`: [$wife->id, $this->id, 'wife']
    }

    public function addRelative($relationship, User $relative) {
        switch ($relationship) {
            case 'child':
                $this->addChild($relative);
                break;

            case 'wife':
                $this->addWife($relative);
                break;

            default:
                throw new Exception("Unknown relationship:" . $relationship);
                break;
        }
    }
    public function saveFamily() 
    {
        $family_leader = new User();
        $family_leader->name = $_POST['family_leader']['name'];
        $family_leader->ic = $_POST['family_leader']['ic'];
        $family_leader->save();
    
        foreach ($_POST['name'] as $i => $name) {
            $family_member = new User();

            $family_member->name = $name;
            $family_member->ic = $_POST['ic'][$i];
            $family_member->save();
    
            try {
                $family_leader->addRelative($_POST['relationship']['$i'], $family_member);
            } catch (Exception $e) {
                die ('Relationship not added:' . $e->getMessage());
            }
        }
    }
}